### ISSUE TITLE
NaN for line height and letter spacing for dynamic font sizes

### ISSUE THREAD

**Issue by semencov** [semencov/tailwindcss-font-inter#3]
Instead of calculated line height and letter spacing got this:

```css
.text-inter-4xl {
  font-size: 36px;
  letter-spacing: NaNem;
  line-height: NaNpx;
}
```
